version: "3"
services:
  abidjan:
    image: geosm_ville
    container_name: geosm_abidjan
    restart: unless-stopped
    tty: true
    volumes:
      - ./public/.env:/var/www/GeoOSM_Backend/.env
      - ./public/assets/config.js:/var/www/GeoOSM_Backend/public/assets/config.js
      - ./public/assets/images/:/var/www/GeoOSM_Backend/public/assets/images/
      - ./public/assets/admin/images/:/var/www/GeoOSM_Backend/public/assets/admin/images/
      - ./public/upload/:/var/www/GeoOSM_Backend/public/upload
      - ./public/download/:/var/www/GeoOSM_Backend/public/download

      - ./client/environments/environment.ts:/var/www/GeoOSM_Frontend/src/environments/environment.ts
      - ./client/environments/color.scss:/var/www/GeoOSM_Frontend/src/environments/color.scss
      - ./client/htaccess.txt:/var/www/GeoOSM_Frontend/htaccess.txt
      - ./client/assets/:/var/www/GeoOSM_Frontend/assets/

      - ./php/php.ini:/etc/php/7.4/cli/conf.d/30local.ini
      - ./vhost-apache/:/etc/apache2/sites-available/
      - ./boot.sh:/var/www/boot.sh

    environment:
      DEFAULT_ROOT: "/"
      WEB_ROOT: /var/www/GeoOSM_Frontend/dist/
    ports:
      - 1004:8060
      - 1005:8070

